import systemHandler from '../api/system.js';
import fs from 'fs';
import path from 'path';

// Parse .env.local manually to load environment variables
try {
    const envPath = path.resolve(process.cwd(), '.env.local');
    if (fs.existsSync(envPath)) {
        const envContent = fs.readFileSync(envPath, 'utf8');
        envContent.split('\n').forEach(line => {
            const trimmed = line.trim();
            if (trimmed && !trimmed.startsWith('#')) {
                const parts = trimmed.split('=');
                const key = parts[0].trim();
                let value = parts.slice(1).join('=').trim();
                // strip quotes if present
                if (value.startsWith('"') && value.endsWith('"')) {
                    value = value.substring(1, value.length - 1);
                } else if (value.startsWith("'") && value.endsWith("'")) {
                    value = value.substring(1, value.length - 1);
                }
                process.env[key] = value;
            }
        });
        console.log("Loaded environment variables from .env.local manually.");
    } else {
        console.error(".env.local file not found!");
    }
} catch (e) {
    console.error("Error reading .env.local:", e);
}

// Mock request and response
const req = {
    method: 'POST',
    query: { action: 'lead' },
    headers: {},
    body: {
        name: "Prince Test (Antigravity)",
        phone: "+91 99999 88888",
        email: "test@quickkitai.com",
        businessName: "Test Property Inc.",
        projectName: "Odoo CRM Integration Test",
        notes: "This is a test lead generated by the Antigravity agent to verify Odoo CRM integration.",
        price: 499
    }
};

const res = {
    headers: {},
    statusCode: 200,
    setHeader(name, value) {
        this.headers[name] = value;
    },
    status(code) {
        this.statusCode = code;
        return this;
    },
    json(data) {
        console.log(`\nResponse Status Code: ${this.statusCode}`);
        console.log("Response Body:", JSON.stringify(data, null, 2));
        return this;
    },
    end() {
        console.log("\nResponse Ended.");
    }
};

console.log("Starting Odoo integration test run...");
systemHandler(req, res).catch(err => {
    console.error("Test execution failed:", err);
});
